### ISSUE TITLE
3.11.0 fails to load on pi 0.85.1: require("../dist/pi-extension.js") cannot resolve @earendil-works/pi-ai/utils/uuid (pi exits at startup)

### ISSUE THREAD

**Issue by swarajban** [QuintinShaw/pi-dynamic-workflows#197]
## Summary

On pi **0.85.1**, `@quintinshaw/pi-dynamic-workflows@3.11.0` fails to load its extension, so **pi exits at startup in every directory**. The only way to start pi is to disable this extension or the whole package.

This looks like a regression from the fix in #186, which repointed the extension entry to a TypeScript file that loads the compiled graph via CJS `require`.

## Environment

- `@earendil-works/pi-coding-agent`: **0.85.1** (latest)
- `@quintinshaw/pi-dynamic-workflows`: **3.11.0** (latest)
- Node: **v24.15.0** (mise-managed)
- OS: macOS (darwin, arm64)
- Extensions loaded through pi's normal startup path (not `-ne`)

## Actual behaviour

```
$ pi
Error: Failed to load extension ".../pi-dynamic-workflows/extensions/workflow.ts": Failed to load extension: Cannot find module '.../pi-coding-agent/node_modules/@earendil-works/pi-ai/dist/compat.js/utils/uuid'
Require stack:
- .../pi-coding-agent/node_modules/@earendil-works/pi-agent-core/dist/harness/session/session.js
Hint: Start without extensions using "pi -ne".
```

Exit code **1**. No TUI starts.

Note the requested path contains `dist/compat.js/utils/uuid`. **That path does not exist** — `compat.js` is a file, not a directory. It looks like a resolver fallback artifact rather than a real lookup.

## Expected behaviour

The extension loads and pi starts.

## Isolation

- `pi -ne` (no extensions): **exit 0**, answers normally.
- `pi` with extensions: **exit 1**, error above.
- Reproduces in a **brand-new empty directory**, so this is not project-specific or config-specific in the user's repo.

One extension breaks the whole startup, so the blast radius is "pi will not open at all".

## Root cause analysis

`extensions/workflow.ts` deliberately loads the compiled graph through CJS `require`:

```ts
// Pi supplies this require through its TypeScript loader. Keep the compiled
// graph synchronous: an async ESM re-export can take jiti's native-import
// shortcut and bypass the host's SDK aliases/virtual modules.
const extension = require("../dist/pi-extension.js") as typeof import("../dist/pi-extension.js");
```

That graph reaches `pi-agent-core`, whose `dist/harness/session/session.js` contains:

```js
import { uuidv7 } from "@earendil-works/pi-ai/utils/uuid";
```

`pi-ai@0.85.1`'s `package.json` declares **only `types` and `import` conditions** — there is no `require` condition for any subpath:

```json
"./utils/*": { "types": "./dist/utils/*.d.ts", "import": "./dist/utils/*.js" }
```

So a **CJS `require` of that bare subpath cannot resolve**. Verified directly on Node 24.15.0:

```js
// Node 24 supports require(esm)
require('<pi-ai>/dist/utils/uuid.js')        // OK    -> [ 'uuidv7' ]
require('@earendil-works/pi-ai/utils/uuid')  // FAIL  -> MODULE_NOT_FOUND
```

The bare package root fails the same way, for the same reason:

```js
require('@earendil-works/pi-agent-core')     // FAIL  -> ERR_PACKAGE_PATH_NOT_EXPORTED
```

So the `require("../dist/pi-extension.js")` hop does **not** keep the compiled graph on jiti's transpiled/`virtualModules` path on pi 0.85.1. The graph's bare `@earendil-works/pi-ai/...` imports fall through to normal `node_modules` resolution, where import-only exports cannot satisfy a `require`.

## What I tried that did NOT work

Adding a `require` condition to `pi-ai`'s exports map (pointing at the same `dist/` files) did **not** fix the load:

```json
"./utils/*": { "types": "...", "import": "...", "require": "./dist/utils/*.js" }
```

Still the same error. That suggests the resolution is happening inside the host's TS loader (`jiti`) rather than through Node's exports matching. **Reverted** — no vendor files were left modified.

## Workaround

Disable just the extension, keeping the package's skills:

```json
{ "source": "npm:@quintinshaw/pi-dynamic-workflows", "extensions": [] }
```

or remove the package entirely. `pi -ne` also starts pi.

## Impact

On pi 0.85.1, `/effort`, `/ultracode`, `/workflows`, and the `workflow` tool are all unavailable, and the package makes pi fail to start until it is disabled.

## Request

Support pi 0.85.x. Suggested directions:

1. Route the extension entry through ESM `import` (or jiti's transpiled path) so `virtualModules` keep serving the host's module instances for the `pi-ai` subpath imports, **or**
2. Avoid the CJS `require` hop into `dist/pi-extension.js` for a `"type": "module"` package, since the compiled graph then resolves bare imports without `virtualModules`, **or**
3. Have pi's `virtualModules` also cover `@earendil-works/pi-ai/*` subpaths so import-only packages can be required.

Happy to test a candidate build against pi 0.85.1.

**Comment by QuintinShaw** [comment]
Confirmed through the actual Pi 0.85.1 unbundled Node extension loader: the old entry reproduces the compat.js/utils/uuid resolution failure. The fix is merged in #200 (fbde13c).

The compiled graph now loads with ESM import semantics, while delivery capture explicitly receives the host AgentSession class. Tests cover both the normal Node alias loader and embedded virtual-module identity. Real Pi startup, background result delivery and reload passed; 1,425 automated tests passed.

This is fixed on main, but no patched npm release has been published yet. The published 3.11.0 package is unchanged. Thank you for the precise reproduction report.

**Comment by swarajban** [comment]
👌🏽

--
Swaraj Banerjee

**Comment by QuintinShaw** [comment]
The startup fix is now available in v3.12.0 on npm. The release was verified through the installed Pi loader, and the publicly downloaded package matches the validated release artifact. Release notes: https://github.com/QuintinShaw/pi-dynamic-workflows/releases/tag/v3.12.0
